### ISSUE TITLE
fetch.POST Example

### ISSUE THREAD

**Issue by pallabseal** [maakbaas/esp8266-iot-framework#107]
Can you provide POST example using fetch class.

**Comment by Eisbaeeer** [comment]
> Can you provide POST example using fetch class.

Hi. You can do that like this example. It is also described in documentation:

// define url and create body
String url = F("www.example.com");
String body = F("Place here the POST-string");

// call fetch function
fetch.begin(url);
fetch.POST(body);

**Comment by majo551** [comment]
@Eisbaeeer  have you figured out the post example? For me personally it is not obvious anwer: 

`POST
int POST(String url, String body);
int POST(String body);
This method starts a POST request to the URL specified in url with the payload specified in body. The URL must include a http:// or https:// prefix. The method returns the HTTP response code. If you first called the begin method, the variant without the url argument should be used.`

I am lost from the documentation example. :-(

**Comment by Eisbaeeer** [comment]
@majo551 Im using POST and get functions from the library. Did you tried the example?

**Comment by majo551** [comment]
> @majo551 Im using POST and get functions from the library. Did you tried the example?

@Eisbaeeer  I must be stupid, but I cannot find  a code example in Examples (both docs or codes)related to POST. Can you please direct me to the right part of the documentation for a working example? Thank you.

**Comment by majo551** [comment]
Can anyone direct me to the example where POST is described in details ? What is meant by body for POST function? Is this just the parameters or the post link or the whole POST structure?  The documentation shows only : 
![image](https://user-images.githubusercontent.com/13347592/138068417-580e163a-13f2-42e5-9fa8-227b3abf40f7.png)

Example shows only GET method:
![image](https://user-images.githubusercontent.com/13347592/138068564-4393f94c-c15b-4a42-be07-ff2716a9a5c2.png)

Have I missed some part with POST explained?
Thanks

I tried to guess:

        //do task
        Serial.println(ESP.getFreeHeap());

        Serial.println("fetch start");

        fetch.POST("https://postman-echo.com/post","id=test");

        Serial.println("fetch done");

        String repl="";
       repl=fetch.readString();

        fetch.clean();
        Serial.println(repl);


But this cause the device reboot...
![image](https://user-images.githubusercontent.com/13347592/138074999-30891f0a-678c-43c9-bca6-a5083a18eafc.png)

**Comment by maakbaas** [comment]
If I follow the GET example but replace the `fetch.GET` line with your:

`
fetch.POST("https://www.postman-echo.com/post","id=test");
`

The code works perfectly fine for me, and I get the response:

`{"args":{},"data":"id=test","files":{},"form":{},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"www.postman-echo.com","x-amzn-trace-id":"Root=1-61865fc6-381c39734b63eef41a3dec28","content-length":"7","user-agent":"ESP8266HTTPClient","accept-encoding":"identity;q=1,chunked;q=0.1,*;q=0","content-type":"application/json"},"json":null,"url":"https://www.postman-echo.com/post"}`

I suspect your reset might be caused because you try to read the entire response string at once, rather than streaming it.

**Comment by vvilho** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/63448548/197684696-51b9ba16-b508-478a-abf6-95998af593e0.png">
I'm getting the same kind of response as @majo551. Is there anything else I need to set up differently to get the real response from the POST request.
