### ISSUE TITLE
compiling does not work

### ISSUE THREAD

**Issue by MatMat81** [maakbaas/esp8266-iot-framework#124]
hey,

how can i compile it?

With this version I get the following error messages:
vscode
platformio
Node.js v17.0.0
npm 8.1.1
OpenSSL-1.1.1h_win32

**Error:**
_LoaderRunner.js:111:13)
    at H:\ESP8266_IoT_Framework_tester_V2\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}_

**Comment by maakbaas** [comment]
This seems to be a compatibility issue between Node.js v17 and webpack 4. 
https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

Workaround implemented in commit c69ab82380ed443708ded91319be7eeaf30d3766

**Comment by maakbaas** [comment]
In fact, after some further testing I have removed this change. 

If you want to keep using Node 17 you would need to set 

`NODE_OPTIONS=--openssl-legacy-provider`

in your own environment. The reason I can't do that from npm scripts, as I tried in that commit is that it will break on all other node versions, since node errors if you try to set a non-existing node option.

Another fix would be to use a <17 Node version.
