### ISSUE TITLE
We should let the user know when wifi connection was successful

### ISSUE THREAD

**Issue by mjangir** [maakbaas/esp8266-iot-framework#128]
This is an awesome project first of all. My unsolicited suggestion is, ideally we should let the user know that the wifi connection was successful. I'm not 100% sure how to do it but what if we change the wifi mode from access point to station mode after sending the http response back to the user or may be we can use STA + AP Mode if possible.

**Comment by maakbaas** [comment]
I agree that this could be a nice addition, if I understand you correctly this is to mitigate the fact that the ESP changes to a new network and therefore can't give feedback about that change to the client that was connected on the old network.

Due to time constraints, new features will currently only be considered in the form of a pull request. For this reason I will close this issue to keep the issues list focussed on bugs or other problems. Thank you for your understanding.
