### ISSUE TITLE
Use relative paths in Dashboard and API

### ISSUE THREAD

**Issue by csiwek** [maakbaas/esp8266-iot-framework#133]
I wanted to expose the dashboard  to the internet by proxying it through nginx, for example:
http://domain.tld/myiotdevice  -> 192.168.1.10
( I know it's not very secure but it is restricted access to a small range of IPs and I added Basic Auth on top of it) 

The issue I'm having is that API paths, WS endpoint, as well as dashboard paths, are absolute so lots of trickery was required to rewrite paths on Nginx and forcing the 'url' variable in index.js. I was wondering if there is a more elegant way of making it configurable or perhaps all paths could be made relative.

**Comment by maakbaas** [comment]
Relative paths can't work for websocket, because it needs to define the full path in order to create the socket connection.

As you have found, the url parameter can be used to change the url used in creating the path for the API connections. Because of the limitation above I don't see an immediate solution that would be more elegant. But open to ideas of course!
