### ISSUE TITLE
Request: click button in dashboard

### ISSUE THREAD

**Issue by Eisbaeeer** [maakbaas/esp8266-iot-framework#159]
How is it possible to create an input button element?
In my case the button should open a webpage from a variable like string or char.

It will be perfect, if this two vars can be defined (action and button text) from code:

`<form action="https://www.w3docs.com/">
         <button type="submit">Click me</button>
      </form>`

cheers Lars

**Comment by maakbaas** [comment]
Hi Lars,

This will not be considered for now, because the button is not what the dashboard is intended for, which is to serve as a method to interact from a GUI with your application. 

I can see the value of adding a link, but for this I would recommend to customize the GUI specific to your project.
