### ISSUE TITLE
Pre build script are not executed on 1.6.1

### ISSUE THREAD

**Issue by marcolino7** [maakbaas/esp8266-iot-framework#56]
Hi,
I ugraded library on a working project, and seems that pre build script are not executed anymore, so the files config.h and config.c are not created with my custom parameter and got compilation errors.
Is there something I have to do in 1.6.1 ?

Marco

**Comment by maakbaas** [comment]
Please read this section of the documentation:

https://github.com/maakbaas/esp8266-iot-framework/blob/master/docs/installation-guide.md#build-options

But yes, the `REBUILD_CONFIG` was enabled by default in the past and not anymore in this build. The reason being that it did not make sense to enable this without enabling also rebuilding the HTML. In one of the future versions I plan to make the pre build scripts more user-friendly so that more things are executed automatically

**Comment by marcolino7** [comment]
thanks
